#
FROM quay.io/ascend/vllm-ascend:v0.18.0-a3
COPY .docker/npu_patch /root/patch
WORKDIR /root
ARG PIP_INDEX_URL="https://mirrors.tuna.tsinghua.edu.cn/pypi/web/simple"

RUN sed -i 's/archive.ubuntu.com/mirrors.tuna.tsinghua.edu.cn/g' /etc/apt/sources.list && \
    sed -i 's/security.ubuntu.com/mirrors.tuna.tsinghua.edu.cn/g' /etc/apt/sources.list
# System dependencies
RUN DEBIAN_FRONTEND=noninteractive apt-get update && apt-get install -y --no-install-recommends \
    build-essential patchelf tmux net-tools htop nano iputils-ping \
    autoconf automake libatlas-base-dev libgoogle-glog-dev libbz2-dev libc-ares2 \
    libleveldb-dev liblmdb-dev libprotobuf-dev libsnappy-dev libtool nasm protobuf-compiler pkg-config unzip sox\
    libsndfile1 libpng-dev libhdf5-dev gfortran rapidjson-dev ninja-build libedit-dev rsync

RUN apt-get install -y locales tzdata && \
    locale-gen "$LANG" && update-locale LANG="$LANG" LC_ALL="$LC_ALL" && \
    ln -snf /usr/share/zoneinfo/$TZ /etc/localtime && echo $TZ > /etc/timezone

RUN apt-get install -y --no-install-recommends \
    libgl1-mesa-glx \
    libglib2.0-0 \
    libsm6 \
    libxext6 \
    libxrender-dev \
    && rm -rf /var/lib/apt/lists/*

# Global config (set once, persists across subsequent RUN layers)
RUN pip config set global.index-url ${PIP_INDEX_URL} && \
    git config --global http.sslverify false && \
    git config --global http.postBuffer 2147483648
RUN git clone https://gitcode.com/Ascend/MindSpeed.git /root/MindSpeed && \
    git clone https://github.com/NVIDIA/Megatron-LM.git /root/Megatron-LM && \
	git clone https://github.com/coding-famer/Megatron-Bridge-slime.git /root/Megatron-Bridge

# Clone MindSpeed (mhh111 fork), Megatron-LM, MindSpeed-Bridge, Megatron-Bridge, and install
RUN cd /root/MindSpeed && git checkout fc63de5c && pip install -r requirements.txt && pip install -e . && \
    cd /root/Megatron-LM  && git checkout 3714d81d4 && pip install -e . && \
	cd /root/Megatron-Bridge && git checkout qwen35

RUN git clone https://github.com/redai-infra/Relax.git /root/Relax && \
    git clone https://github.com/sgl-project/sgl-kernel-npu.git /root/sgl-kernel-npu && \
	git clone https://github.com/sgl-project/sglang.git /root/sglang

# Clone sglang (v0.5.10, includes transformers ~5.3.0) and sgl-kernel-npu, install
RUN cd /root/sglang/python && \
    git fetch origin pull/23815/head:pr-23815 && \
	git checkout pr-23815 && \
    rm -rf pyproject.toml && \
    mv pyproject_npu.toml pyproject.toml && \
    pip install -v -e .[all_npu] && \
    cd /root/sgl-kernel-npu && \
	git checkout 2026.04.15.rc3 && \
    bash build.sh && \
    pip install output/*.whl && \
    cd /root/Relax && pip install -r requirements.txt && pip install -e .

# Install extra packages (tensordict, transferqueue, modelopt) and deep-ep symlink
RUN pip install --no-cache-dir tensordict==0.10.0 pyvers==0.1.0 --no-deps && \
    pip install "transferqueue @ git+https://github.com/redai-infra/TransferQueue.git" --no-deps -i https://pypi.tuna.tsinghua.edu.cn/simple && \
	pip install nvidia-modelopt && \
    pip install setuptools==79.0.1 fla-core flash-linear-attention && \
    cd "$(python3 -m pip show deep-ep | awk '/^Location:/ {print $2}')" && ln -sf deep_ep/deep_ep_cpp*.so

# Apply NPU patches
RUN cd /root/MindSpeed && \
    patch -p1 < /root/patch/0001-support-qwen35-and-gdn-fusion-kernel.patch && \
	patch -p1 < /root/patch/0001-fix-Add-mindspeed-config-to-subclass-of-transformer-.patch && \
    cd /root/Megatron-Bridge && \
    patch -p1 < /root/patch/0001-add-mindspeed-mapping-remove-nvtx.patch && \
	patch -p1 < /root/patch/0001-megatron-bridge.patch && \
    cd /root/Megatron-LM && \
    patch -p1 < /root/patch/0001-use-triton-gdn-fusion-ops.patch && \
    cd /root/sgl-kernel-npu && \
	patch -p1 < /root/patch/0001-tms-adapt-colacate.patch && \
	cd /root/patch && \
	pip install torch_npu-*.whl

ENV PYTHONPATH=/root/Megatron-Bridge/src:/root/MindSpeed:/root/Megatron-LM:$PYTHONPATH

CMD ["/bin/bash"]
